// ACTIONS - Contacts
export const LOADING_CONTACTS = 'LOADING_CONTACTS';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const POST_CONTACT = 'POST_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACTS = 'DELETE_CONTACTS';

// ACTIONS - Error
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
